name: mysnap2 # you probably want to 'snapcraft register <name>'
version: '0.2' # just for humans, typically '1.2+git' or '1.3.2'
base: core20
summary: Single-line elevator pitch for your amazing snap # 79 char long summary
description: |
  This is my-snap's description. You have a paragraph or two to tell the
  most important story about your snap. Keep it under 100 words though,
  we live in tweetspace and your description wants to look good in the snap
  store.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: strict

parts:
  my-service:
    plugin: dump
    source: src/

apps:
  hellod:
    command: bin/hellod
    daemon: simple
    plugs:
      - network-bind
      - system-observe
    sockets:
      unix:
        listen-stream: $SNAP_COMMON/my2.socket
        socket-mode: 0777
